const songNames = [
	"pissing in my jeans",
	"stuck in a khole",
	"obliterated on a monday",
	"i can fix them",
	"having a panic attack",
	"peaked in college",
	"anxious-avoidant",
	"where’s my vape",
	"yakking in the uber",
	"$12 in my bank account",
	"in a downward spiral",
	"derogatory",
	"losing my mind",
	"unemployed",
	"flop era",
	"failed microinfluencer",
	"chronically online",
	"dissociating at the function",
	"delusional",
	"constipated",
	"no bitches",
	"unironically cringe",
	"mental illness",
	"depressed",
	"no thoughts head empty",
	"seriously troubled",
	"commitment issues",
	"pick me",
	"ran through",
	"socially awkward",
	"getting ghosted",
	"farting in the club",
	"pathetic loser",
	"get a load of this moron",
	"insufferable nerd",
	"beta",
	"killing myself",
	"problematic",
	"toxic",
	"major catfish",
	"kinda ugly",
	"funny looking",
	"attention whore",
	"annoying",
	"ew",
	"suffering",
	"borderline alcoholic",
	"a little slow",
	"aging poorly",
	"wetting the bed",
	"gets bullied by children",
	"unfunny",
	"lowkey stinky",
	"at rock bottom",
	"nothing special",
	"has no life",
	"a bit much",
	"forgettable"
];

export {songNames};